### PR TITLE
Reference Manual Outline

### PR DESCRIPTION
**Pull request by tajmone**
Add to `docs-src/ref-man/` folder the AsciiDoc skeleton
of the ToolMaker Reference Manual, with all the book Parts
and their Introduction in place, along with the plain-text
OCR working file.

New `refman` Rake task to build the manual, also included
in the default task.

### CODE REVIEW

**Comment by tajmone** [comment]
Please, rebase-merge (no merge commit) so we keep the commit text.

**Comment by thoni56** [comment]
> Please, rebase-merge (no merge commit) so we keep the commit text.

Yup. All types where enabled and unfortunately Merge is what comes out on top then. I've disabled the other two so rebase&merge is the only one enabled now.

**Comment by thoni56** [comment]
@tajmone Filenames needs to be quoted, especially if you have `(` in them, like for the man pages. Otherwise:

```
*** TASK FAILED! *******************************************************

Asciidoctor conversion failed: docs-src/man-pages/imp(1).asciidoc
------------------------------------------------------------------------
sh: -c: line 0: syntax error near unexpected token `('
sh: -c: line 0: `asciidoctor --failure-level WARN --verbose --timings --safe-mode unsafe -a source-highlighter=rouge -a rouge-style=thankful_eyes -D /cygdrive/c/Users/Thomas/Utveckling/ToolMaker/doc imp(1).asciidoc'
************************************************************************
```

**Comment by tajmone** [comment]
> @tajmone Filenames needs to be quoted, especially if you have ( in them, like for the man pages

I'll try and fix the Rakefile, but since I'm not getting that error under Windows (even in Bash) you'll have to confirm to me that it works.

**Comment by thoni56** [comment]
> > @tajmone Filenames needs to be quoted, especially if you have ( in them, like for the man pages
> 
> I'll try and fix the Rakefile, but since I'm not getting that error under Windows (even in Bash) you'll have to confirm to me that it works.

You can point me to where I should look and I can try it out.

**Comment by tajmone** [comment]
See PR #12: I've wrapped the filename within quotes when invoking Asciidoctor.

Let me know if this fixes the problem, since on my Win 10 machine it worked fine both before and after this fix (tried with CMD and Bash).

**Pull request merged**
